# Check the documentation at http://goreleaser.com
project_name: odm
builds:
  -
    main: ./cmd/odm/main.go
  - env:
    - CGO_ENABLED=0
archive:
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
